import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  // const hello = api.posts.hello.useQuery({ text: "from tRPC" });

  const user = useUser()

const {data} = api.posts.getAll.useQuery()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#bfbac7] to-[#030ed8]">
        <div>
          
          {!user.isSignedIn ? <SignInButton /> : null}
          {user.isSignedIn ? <SignOutButton /> : null}
        </div>
        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}

        <div>
          {data?.map((post, index)=> {
            return (
              <div key={index}>
                  {post.content}
              </div>
            )
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
